/*
  Warnings:

  - The values [MEMBER_EXIT_WITHDRAW,MEMBER_EXIT_PROFIT_WITHDRAW] on the enum `TRANSACTION_MODE` will be removed. If these variants are still used in the database, this will fail.

*/
-- AlterEnum
BEGIN;
CREATE TYPE "TRANSACTION_MODE_new" AS ENUM ('MEMBERS_PERIODIC_DEPOSIT', 'MEMBERS_WITHDRAW', 'MEMBERS_WITHDRAW_PROFIT', 'NEW_MEMBER_PAST_TALLY', 'INTER_CASH_TRANSFER', 'VENDOR_PERIODIC_INVEST', 'VENDOR_PERIODIC_RETURN', 'VENDOR_INVEST', 'VENDOR_RETURN', 'OTHER_EXPENDITURE');
ALTER TABLE "Transaction" ALTER COLUMN "mode" DROP DEFAULT;
ALTER TABLE "Transaction" ALTER COLUMN "mode" TYPE "TRANSACTION_MODE_new" USING ("mode"::text::"TRANSACTION_MODE_new");
ALTER TYPE "TRANSACTION_MODE" RENAME TO "TRANSACTION_MODE_old";
ALTER TYPE "TRANSACTION_MODE_new" RENAME TO "TRANSACTION_MODE";
DROP TYPE "TRANSACTION_MODE_old";
ALTER TABLE "Transaction" ALTER COLUMN "mode" SET DEFAULT 'MEMBERS_PERIODIC_DEPOSIT';
COMMIT;
