/*
  Warnings:

  - The values [GROUPS,MEMBERS,VENDORS,PERIODIC_DEFAULT,PERIODIC_GROUP,PERIODIC_USER] on the enum `SUMMARY_TYPE` will be removed. If these variants are still used in the database, this will fail.

*/
-- AlterEnum
BEGIN;
CREATE TYPE "SUMMARY_TYPE_new" AS ENUM ('DEFAULT', 'GROUP', 'MEMBER', 'VENDOR');
ALTER TABLE "Summary" ALTER COLUMN "type" DROP DEFAULT;
ALTER TABLE "Summary" ALTER COLUMN "type" TYPE "SUMMARY_TYPE_new" USING ("type"::text::"SUMMARY_TYPE_new");
ALTER TYPE "SUMMARY_TYPE" RENAME TO "SUMMARY_TYPE_old";
ALTER TYPE "SUMMARY_TYPE_new" RENAME TO "SUMMARY_TYPE";
DROP TYPE "SUMMARY_TYPE_old";
ALTER TABLE "Summary" ALTER COLUMN "type" SET DEFAULT 'DEFAULT';
COMMIT;
